// Regenerates fixtures/next-base and fixtures/next-radix from the live shadcn registry.
// Apps are generated in a temp dir (so shadcn doesn't pick up this repo's pnpm lockfile), then copied in.
// Usage:  node fixtures/create.mjs                          pinned shadcn CLI (fixtures/tested.json)
//         SHADCN_VERSION=latest node fixtures/create.mjs    re-test after `pnpm drift` finds a change
import { execSync } from "node:child_process"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"

import { withRegistry } from "./registry-server.mjs"
import { SHADCN_CLI } from "./tested.mjs"

const HERE = path.dirname(new URL(import.meta.url).pathname)
const CLI = `shadcn@${SHADCN_CLI}`
const BASES = (process.env.KF_BASES ?? "base,radix").split(",")
const sh = (cmd, cwd) => execSync(cmd, { cwd, stdio: "inherit", env: { ...process.env, npm_config_user_agent: "npm/11.8.0 node/v24" } })
const skip = (src) => !/[/\\](node_modules|\.next)([/\\]|$)/.test(src)

async function exampleNames(base) {
  const reg = await (await fetch(`https://ui.shadcn.com/r/styles/${base}-nova/registry.json`)).json()
  return reg.items.filter((i) => i.type === "registry:example").map((i) => i.name).sort()
}

function patchLayout(app) {
  const file = path.join(app, "app/layout.tsx")
  let s = fs.readFileSync(file, "utf8")
  s = s.replace(
    'import "./globals.css"\n',
    'import "./globals.css"\nimport { Suspense } from "react"\nimport { FixtureToaster } from "@/components/kf-fixture/extra"\nimport { KfCuts } from "@/components/kf-fixture/kf-cuts"\nimport { Toaster } from "@/components/ui/sonner"\n',
  )
  s = s.replace(
    "<ThemeProvider>{children}</ThemeProvider>",
    "<ThemeProvider>\n          {children}\n          <Toaster />\n          <FixtureToaster />\n          <Suspense>\n            <KfCuts />\n          </Suspense>\n        </ThemeProvider>",
  )
  if (!s.includes("<KfCuts />")) throw new Error("app/layout.tsx did not have the expected shape: update patchLayout()")
  fs.writeFileSync(file, s)
}

function writeSinkIndex(app, names) {
  // Examples that need an AI backend (@/lib/ai, @ai-sdk/*) can't run in a fixture.
  // Also skip examples that import pages of shadcn's own site (an "@/..." path the app doesn't have).
  const resolves = (spec) => ["", ".tsx", ".ts", "/index.tsx", "/index.ts"].some((ext) => fs.existsSync(path.join(app, spec + ext)))
  const needsBackend = (n) => {
    const src = fs.readFileSync(path.join(app, "components", `${n}.tsx`), "utf8")
    if (/from "(@\/lib\/ai|@ai-sdk\/)/.test(src)) return true
    return [...src.matchAll(/from "@\/([^"]+)"/g)].some((m) => !resolves(m[1]))
  }
  const file = (n) => path.join(app, "components", `${n}.tsx`)
  const exists = names.filter((n) => fs.existsSync(file(n)))
  for (const n of exists.filter(needsBackend)) fs.rmSync(file(n))
  const present = exists.filter((n) => fs.existsSync(file(n)) && /export default/.test(fs.readFileSync(file(n), "utf8")))
  const lines = present.map((n) => `  ${JSON.stringify(n)}: () => import("@/components/${n}"),`)
  fs.mkdirSync(path.join(app, "app/sink"), { recursive: true })
  fs.writeFileSync(
    path.join(app, "app/sink/examples.ts"),
    `// Generated by fixtures/create.mjs. Do not edit.\nimport type { ComponentType } from "react"\n\nexport const EXAMPLES: Record<string, () => Promise<{ default: ComponentType }>> = {\n${lines.join("\n")}\n}\n`,
  )
  fs.writeFileSync(path.join(app, "app/sink/examples.json"), JSON.stringify(present, null, 2) + "\n")
  return present.length
}

await withRegistry(async () => {
  for (const base of BASES) {
    const name = `next-${base}`
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "kf-fixture-"))
    sh(`npx -y ${CLI} init -t next -b ${base} -p nova -n ${name} --no-monorepo -y`, tmp)
    const app = path.join(tmp, name)
    sh(`npx -y ${CLI} add --all -y -o`, app)
    const names = await exampleNames(base)
    sh(`npx -y ${CLI} add ${names.join(" ")} -y -o`, app)
    for (const dir of ["shared/common", `shared/variants/${base}`, "shared/variants/cuts"]) fs.cpSync(path.join(HERE, dir), app, { recursive: true })
    const count = writeSinkIndex(app, names)
    patchLayout(app)
    const cfgFile = path.join(app, "components.json")
    const cfg = JSON.parse(fs.readFileSync(cfgFile, "utf8"))
    cfg.registries = { ...(cfg.registries ?? {}), "@keyframery": "http://localhost:4400/r/{name}.json" }
    fs.writeFileSync(cfgFile, JSON.stringify(cfg, null, 2) + "\n")
    sh(`npx -y ${CLI} add @keyframery/cuts -y -o`, app)
    const dest = path.join(HERE, name)
    fs.rmSync(dest, { recursive: true, force: true })
    fs.cpSync(app, dest, { recursive: true, filter: skip })
    fs.rmSync(path.join(dest, ".git"), { recursive: true, force: true }) // shadcn init makes its own repo
    sh("npm install", dest)
    console.log(`created fixtures/${name} (${count} examples)`)
  }
})
