import { expect, test } from "./kit"

test("changing a menu and a slider updates the code, and Share restores it", async ({ page, context }, info) => {
  test.skip(info.project.name !== "chromium", "clipboard permissions are Chromium-only in Playwright")
  await context.grantPermissions(["clipboard-read", "clipboard-write"])
  await page.goto("/theme")
  await page.getByRole("radio", { name: "punch-in" }).first().click()
  await expect(page.getByTestId("theme-jsx")).toHaveText('<Cuts dialog="punch-in" />')
  await page.getByRole("button", { name: "Share" }).click()
  const url = await page.evaluate(() => navigator.clipboard.readText())
  expect(url).toContain("/theme?dialog=punch-in")
  await page.goto(url)
  await expect(page.getByTestId("theme-jsx")).toHaveText('<Cuts dialog="punch-in" />')
  expect(await page.evaluate(() => document.documentElement.getAttribute("data-kf-dialog"))).toBe("punch-in")
})

test("leaving the Theme page puts the site's own cuts back", async ({ page }) => {
  await page.goto("/theme?dialog=fade&pace=2")
  expect(await page.evaluate(() => document.documentElement.getAttribute("data-kf-dialog"))).toBe("fade")
  // On phones the nav links sit behind the menu toggle.
  if (!(await page.getByRole("link", { name: "Docs" }).first().isVisible())) await page.getByRole("button", { name: "Toggle Menu" }).click()
  await page.getByRole("link", { name: "Docs" }).first().click()
  await expect(page).toHaveURL(/\/docs/)
  await expect.poll(() => page.evaluate(() => document.documentElement.getAttribute("data-kf-dialog"))).toBe("rack-focus")
  expect(await page.evaluate(() => document.documentElement.style.getPropertyValue("--kf-pace"))).toBe("")
})

test("Copy gives the <Cuts> line and the CSS", async ({ page, context }, info) => {
  test.skip(info.project.name !== "chromium", "clipboard permissions are Chromium-only in Playwright")
  await context.grantPermissions(["clipboard-read", "clipboard-write"])
  await page.goto("/theme?blur=4&tabs=whip")
  await page.getByRole("button", { name: "Copy the code" }).click()
  const text = await page.evaluate(() => navigator.clipboard.readText())
  expect(text).toContain('<Cuts tabs="whip" />')
  expect(text).toContain("--kf-blur: 4px;")
})

test("profiles configure the engine and keep rack-focus controls scoped", async ({ page }) => {
  await page.goto("/theme")
  await expect(page.getByRole("radio", { name: "Expressive", exact: true })).toHaveAttribute("aria-checked", "true")
  await page.getByRole("radio", { name: "Quiet", exact: true }).click()
  await expect(page.getByTestId("theme-jsx")).toContainText('dialog="fade"')
  await expect(page.getByTestId("theme-jsx")).toContainText('pace={0.9}')
  await expect.poll(() => page.evaluate(() => document.documentElement.getAttribute("data-kf-dialog"))).toBe("fade")
  await expect(page.getByRole("slider", { name: "Travel", exact: true })).toBeDisabled()
  await page.getByRole("radio", { name: "Crisp", exact: true }).click()
  await expect(page.getByTestId("theme-jsx")).toContainText('tabs="whip"')
  await expect(page.getByTestId("theme-css")).toContainText("cubic-bezier(0.2, 0.9, 0.1, 1)")
  await page.getByRole("radio", { name: "Expressive", exact: true }).click()
  await expect(page.getByRole("slider", { name: "Travel", exact: true })).toBeEnabled()
  await expect(page.getByTestId("theme-jsx")).toHaveText("<Cuts />")
})

test("one workflow creates, updates, opens and removes a record", async ({ page, errors }) => {
  // Install before navigation as recommended by Playwright, then let the workflow run normally.
  // Pause only the reload sequence so a busy test machine cannot skip its short skeleton phase.
  await page.clock.install({ time: new Date("2026-01-01T00:00:00Z") })
  await page.goto("/theme")
  await page.getByRole("button", { name: "Create record", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Create a record" })
  await dialog.getByRole("textbox", { name: "Record name" }).fill("Release notes")
  await dialog.getByRole("button", { name: "Save record" }).click()
  await expect(dialog.getByRole("status")).toHaveText("Saving your record…")
  await expect(dialog.getByRole("button", { name: "View records" })).toBeVisible()
  await dialog.getByRole("button", { name: "View records" }).click()
  await expect(page.getByTestId("preview-record")).toHaveCount(3)
  await expect(page.getByTestId("preview-record-count").locator("[data-kf-text]")).toHaveText("3")
  const status = page.getByRole("button", { name: "Change status for Release notes" })
  await status.click()
  await expect(status.locator("[data-kf-text]")).toHaveText("Ready")
  await page.getByRole("button", { name: "Release notes", exact: true }).click()
  await expect(page.getByRole("dialog", { name: "Record details" })).toContainText("Status: Ready")
  await page.getByRole("dialog", { name: "Record details" }).getByRole("button", { name: "Close" }).click()
  await page.getByRole("button", { name: "Remove Release notes" }).click()
  await expect(page.getByTestId("preview-record")).toHaveCount(2)
  await page.getByRole("tab", { name: "Activity", exact: true }).click()
  await expect(page.getByText("Workspace synced", { exact: true })).toBeVisible()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 60_000))
  await page.getByRole("button", { name: "Reload activity" }).click()
  const loader = page.getByRole("tabpanel", { name: "Activity", exact: true }).locator('[data-slot="load-cut"]')
  await expect(loader).toHaveAttribute("aria-busy", "true")
  await expect(loader.getByLabel("Loading activity")).toHaveCount(0)
  await page.clock.runFor(350)
  await expect(loader.getByLabel("Loading activity")).toBeVisible()
  await expect(loader).toHaveAttribute("aria-busy", "true")
  await page.clock.runFor(1000)
  await expect(loader).not.toHaveAttribute("aria-busy", "true")
  // React schedules the settling phase after the loaded render. Drain its zero-delay phase timer
  // until that commit exists, then let the real WAAPI dissolve finish before advancing cleanup.
  await expect.poll(async () => {
    await page.clock.runFor(1)
    return loader.locator(':scope > [data-kf-load="content"]').count()
  }).toBe(1)
  await loader.evaluate(async (element) => {
    await Promise.allSettled(element.getAnimations({ subtree: true }).map((animation) => animation.finished))
  })
  await page.clock.runFor(500)
  await expect(loader.locator(':scope > [data-kf-load="skeleton"]')).toHaveCount(0)
  await expect(loader.getByLabel("Loading activity")).toHaveCount(0)
  await expect(loader.getByText("Workspace synced", { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test("closing a pending create cancels its record insertion", async ({ page }) => {
  await page.clock.install({ time: new Date("2026-01-01T00:00:00Z") })
  await page.goto("/theme")
  await page.getByRole("button", { name: "Create record", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Create a record" })
  await expect(dialog.getByRole("textbox", { name: "Record name" })).toBeVisible()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 60_000))
  await dialog.getByRole("button", { name: "Save record" }).click()
  await expect(dialog.getByRole("status")).toHaveText("Saving your record…")
  await dialog.getByRole("button", { name: "Close" }).click()
  await page.clock.runFor(1000)
  await page.clock.resume()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByTestId("preview-record")).toHaveCount(2)
  await page.getByRole("button", { name: "Create record", exact: true }).click()
  await expect(dialog.getByRole("textbox", { name: "Record name" })).toBeVisible()
})

test("named themes persist, export and import without applying invalid JSON", async ({ page }) => {
  await page.goto("/theme")
  await page.getByRole("radio", { name: "Crisp", exact: true }).click()
  await page.getByRole("textbox", { name: "Theme name" }).fill("Launch motion")
  await page.getByRole("button", { name: "Save theme", exact: true }).click()
  await expect(page.getByRole("button", { name: "Load Launch motion" })).toBeVisible()
  await page.reload()
  await expect(page.getByRole("button", { name: "Load Launch motion" })).toBeVisible()
  await page.getByRole("button", { name: "Reset", exact: true }).click()
  await page.getByRole("button", { name: "Load Launch motion" }).click()
  await expect(page.getByRole("radio", { name: "Crisp", exact: true })).toHaveAttribute("aria-checked", "true")
  const downloadPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Download JSON" }).click()
  const download = await downloadPromise
  const path = await download.path()
  expect(path).toBeTruthy()
  expect(download.suggestedFilename()).toBe("launch-motion.json")
  await page.getByRole("button", { name: "Reset", exact: true }).click()
  await page.getByLabel("Import theme JSON", { exact: true }).setInputFiles(path!)
  await expect(page.getByRole("radio", { name: "Crisp", exact: true })).toHaveAttribute("aria-checked", "true")
  await page.getByLabel("Import theme JSON", { exact: true }).setInputFiles({ name: "broken.json", mimeType: "application/json", buffer: Buffer.from('{"version":1,"settings":{"menus":{"dialog":"explode"}}}') })
  await expect(page.locator("main").getByRole("alert")).toBeVisible()
  await expect(page.getByRole("radio", { name: "Crisp", exact: true })).toHaveAttribute("aria-checked", "true")
  await page.getByRole("button", { name: "Remove saved theme Launch motion" }).click()
  await expect(page.getByRole("button", { name: "Load Launch motion" })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole("button", { name: "Load Launch motion" })).toHaveCount(0)
})

test("back and forward restore URL settings and leaving clears all overrides", async ({ page }) => {
  await page.goto("/theme?dialog=fade&pace=2&ease=gentle&blur=4")
  await page.evaluate(() => history.pushState(null, "", "/theme?dialog=punch-in&pace=0.8&ease=snappy"))
  await expect(page.getByTestId("theme-jsx")).toContainText('dialog="punch-in"')
  await page.goBack()
  await expect(page.getByTestId("theme-jsx")).toContainText('dialog="fade"')
  await expect(page.getByTestId("theme-jsx")).toContainText("pace={2}")
  await page.goForward()
  await expect(page.getByTestId("theme-jsx")).toContainText('dialog="punch-in"')
  if (!(await page.getByRole("link", { name: "Docs" }).first().isVisible())) await page.getByRole("button", { name: "Toggle Menu" }).click()
  await page.getByRole("link", { name: "Docs" }).first().click()
  await expect(page).toHaveURL(/\/docs/)
  await expect.poll(() => page.evaluate(() => document.documentElement.getAttribute("data-kf-dialog"))).toBe("rack-focus")
  expect(await page.evaluate(() => ["pace", "ease", "ease-exit", "travel", "blur", "depth", "hold"].map((name) => document.documentElement.style.getPropertyValue(`--kf-${name}`)))).toEqual(["", "", "", "", "", "", ""])
})

test("clipboard failures are reported without claiming a successful copy", async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, "clipboard", { value: { writeText: async () => { throw new Error("Clipboard permission denied") } }, configurable: true }))
  await page.goto("/theme")
  await page.getByRole("button", { name: "Copy the code" }).click()
  await expect(page.locator("main").getByRole("alert")).toContainText("Clipboard permission denied")
  await expect(page.getByRole("button", { name: "Copy the code" })).toHaveText("Copy the code")
})

test("builder fits the viewport", async ({ page }) => {
  await page.goto("/theme")
  const width = page.viewportSize()?.width ?? 0
  expect(await page.evaluate((viewport) => document.documentElement.scrollWidth <= viewport + 1, width)).toBe(true)
})

test("motion profile, cut and easing radios support keyboard selection and one tab stop", async ({ page }) => {
  await page.goto("/theme")
  const profiles = page.getByRole("radiogroup", { name: "Motion profile", exact: true })
  await expect(profiles.locator('[tabindex="0"]')).toHaveCount(1)
  const expressive = profiles.getByRole("radio", { name: "Expressive", exact: true })
  await expressive.focus()
  await expressive.press("ArrowRight")
  const quiet = profiles.getByRole("radio", { name: "Quiet", exact: true })
  await expect(quiet).toBeFocused()
  await expect(quiet).toHaveAttribute("aria-checked", "true")
  await quiet.press("End")
  await expect(expressive).toBeFocused()
  await expect(expressive).toHaveAttribute("aria-checked", "true")
  await expressive.press("Home")
  await expect(quiet).toBeFocused()
  await quiet.press("ArrowDown")
  const crisp = profiles.getByRole("radio", { name: "Crisp", exact: true })
  await expect(crisp).toBeFocused()
  await expect(crisp).toHaveAttribute("aria-checked", "true")
  await expect(profiles.locator('[tabindex="0"]')).toHaveCount(1)

  const dialogCuts = page.getByRole("radiogroup", { name: "Dialog, alert dialog, command", exact: true })
  const punch = dialogCuts.getByRole("radio", { name: "punch-in", exact: true })
  await punch.focus()
  await punch.press("ArrowUp")
  const rack = dialogCuts.getByRole("radio", { name: "rack-focus", exact: true })
  await expect(rack).toBeFocused()
  await expect(rack).toHaveAttribute("aria-checked", "true")
  await expect(page.getByTestId("theme-jsx")).not.toContainText('dialog="punch-in"')
  await rack.press("ArrowLeft")
  const none = dialogCuts.getByRole("radio", { name: "none", exact: true })
  await expect(none).toBeFocused()
  await expect(none).toHaveAttribute("aria-checked", "true")
  await expect(dialogCuts.locator('[tabindex="0"]')).toHaveCount(1)

  const eases = page.getByRole("radiogroup", { name: "Easing in", exact: true })
  const snappy = eases.getByRole("radio", { name: "Snappy", exact: true })
  await snappy.focus()
  await snappy.press("ArrowRight")
  const gentle = eases.getByRole("radio", { name: "Gentle", exact: true })
  await expect(gentle).toBeFocused()
  await expect(gentle).toHaveAttribute("aria-checked", "true")
  await expect(page.getByTestId("theme-css")).toContainText("cubic-bezier(0.4, 0, 0.2, 1)")
  await expect(eases.locator('[tabindex="0"]')).toHaveCount(1)
})
